param(
	[switch]$DryRun
)

# Any file whose path contains one of these directory names (anywhere in the
# path, not just top-level) is skipped entirely. Add more third-party/vendor
# directory names here as needed.
$excludeDirs = @(
	"googletest"
	"todo"
)

$rootDir = $PSScriptRoot
$outputFile = Join-Path $rootDir "\source\engine\todo.h"

Write-Host "Scanning $rootDir for .h, .cpp, .inl files..."

$allFiles = Get-ChildItem -Path $rootDir -Recurse -Include *.h, *.cpp, *.inl -File

# Build a regex alternation from the exclude list once, rather than looping
# over $excludeDirs for every single file -- cheap for 185 files, but this
# keeps it cheap even if the tree grows a lot larger.
if ($excludeDirs.Count -gt 0) 
{
	$excludePattern = ($excludeDirs | ForEach-Object { [regex]::Escape($_) }) -join "|"
	$files = $allFiles | Where-Object { $_.FullName -notmatch $excludePattern }
	$excludedCount = $allFiles.Count - $files.Count
	Write-Host "Found $($allFiles.Count) files, excluding $excludedCount under [$($excludeDirs -join ', ')], scanning $($files.Count)."
}
else 
{
	$files = $allFiles
	Write-Host "Found $($files.Count) files to scan."
}

$pragmaLines = New-Object System.Collections.Generic.List[string]
$pragmaLines.Add("// !! generated by build_todo.ps1  do not edit manually !!")
$pragmaLines.Add("#include `"debug/preprocessor_messages.h`"")
$pragmaLines.Add("")
$filesScanned = 0
$todosFound = 0

foreach ($file in $files)
{
	$filesScanned++
	if ($filesScanned % 500 -eq 0)
	{
		Write-Host "  ...scanned $filesScanned / $($files.Count) files, $todosFound TODOs found so far"
	}

	# Escaped once per file (not per matched line) since it's the same value
	# for every line in this file. C++ string literals treat \ as an escape
	# introducer, so a raw Windows path needs every \ doubled to \\ or the
	# compiler will misread sequences like \U, \g, \s as escape codes rather
	# than literal backslash-plus-letter.
	$escapedPath = $file.FullName.Replace('\', '\\')

	# ReadAllLines avoids the encoding surprises Select-String's default
	# pipeline can have on very large files, and lets us index line numbers
	# directly (1-based, matching what a human/editor would call "line N").
	$lines = [System.IO.File]::ReadAllLines($file.FullName)

	for ($i = 0; $i -lt $lines.Length; $i++) 
	{
		$line = $lines[$i]

		# Case-insensitive substring match. PowerShell's -match operator is
		# case-insensitive by default (there's a case-sensitive -cmatch, but
		# plain -match is what we want here).
		if ($line -match "todo" -and $line -match "//" -and !($line -match "FEATURE_TODO_MESSAGES")) 
		{
			$todosFound++
			$lineNumber = $i + 1

			# Strip the leading "// TODO" marker (any number of slashes,
			# any case, optional : - , separator) since every match here is
			# already known to be that marker -- keeping it in the message
			# would just be restating "this is a todo" inside the todo text.
			# Only the LEADING marker is stripped; "todo" appearing later in
			# the message (e.g. a filename reference) is left untouched.
			$messageOnly = $line -replace '^\s*/{2,}\s*todo\s*[:\-,]?\s*', ''

			# Strip double quotes so the generated string literal isn't broken.
			# No other escaping is needed -- unlike batch, this is just string
			# data, not text that gets re-parsed as shell syntax.
			$cleanLine = $messageOnly.Replace('"', '')

			# If nothing real is left after stripping the marker and quotes
			# (a bare "// TODO" with no description, or trailing whitespace
			# only), fall back to "TODO" so the pragma message isn't blank.
			# Checked AFTER both strips, not before, so a message that's
			# left with only whitespace or only a stray quote character
			# still correctly counts as "no real message".
			if ([string]::IsNullOrWhiteSpace($cleanLine)) 
			{
				$cleanLine = "TODO"
			}

			$pragmaLines.Add("#pragma CUSTOM_MESSAGE_FILE_LINE(`"$escapedPath`", $lineNumber, `"$cleanLine`")")
		}
	}
}

Write-Host "Done scanning. $todosFound TODOs found across $filesScanned files."

if ($DryRun) 
{
	Write-Host "--- DRY RUN: would write the following to $outputFile ---"
	$pragmaLines | ForEach-Object { Write-Host $_ }
	Write-Host "--- DRY RUN: nothing was written to disk ---"
}
else 
{
	$pragmaLines | Set-Content -Path $outputFile -Encoding UTF8
	Write-Host "Wrote $($pragmaLines.Count) TODOs to $outputFile"
}